version: '2.3'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    restart: unless-stopped
    environment:
      MAX_CONURRENT_TASKS: ${PORT:-8}
